### ISSUE TITLE
Не промаркирован параметризированный тест

### ISSUE THREAD

**Issue by kot9pa** [k-belova/python_autotests_project#1]
Тест-кейс **test_guest_can_add_product_to_basket**
`test_product_page.py#L21`
Реализованный в задании
https://stepik.org/lesson/201964/step/4?unit=176022

Должен быть промаркирован **need_review** для рецензии
@pytest.mark.need_review

Согласно заданию https://stepik.org/lesson/201964/step/14?unit=176022

Итого запускается только 4 теста
> collected 22 items / 18 deselected / 4 selected

**Comment by k-belova** [comment]
Промаркирован @pytest.mark.need_review
4 теста и должно запускаться вместе с этим
